### ISSUE TITLE
Depth Not Properly being Tracked

### ISSUE THREAD

**Issue by maximvoven** [avbotz/Nautical#3]
Depth is improperly being tracked, need to recalculate values being used to accurately determine depth. Probably only need to adjust value 230.0 to something else. Alternatively Electrical could be asked to try diffrent supply Voltage 
https://github.com/avbotz/Nautical/blob/240468f27d2eadc80db45db4342c063eae5365c5/src/main.cpp#L270

**Comment by maximvoven** [comment]
Electrical Messed up, Issue closed as no software resolution exsists.

**Comment by rainwaffles** [comment]
LOL as always, it's never a software issue
